bottle-note/bottle-note-frontend

- .gitignore
- src/app/(custom)/login/page.tsx
- src/app/api/auth/[...nextauth]/route.ts
소셜 로그인 OAuth Server 연동
* 체크리스트
- #22 
* 로그인 api 연동 밑작업
* 로컬로 실행 후 localhost:3000/login 경로에서 테스트 가능
* 구글 로그인의 경우 테스트용으로 등록된 구글 계정만 가능하므로 테스트 원하면 계정 추가 요청 바람
* 애플로그인은 비용 이슈로 잠시 보류
* 디자인 적용되지 않은 관계로 추후 수정 예정
* api 요청 로직은 제외됨, 구조 어떻게 가져갈 것인지 ~ api 에서 api로 요청 어떤식으로 보내는지 확인 후 적용 예정
* 소셜로그인 키값은 디스코드로 공유, .env 생성하여 각자 적용 필요
> [#22] 소셜 로그인 OAuth Server 연동

- src/app/(primary)/rating/page.tsx
- src/app/(primary)/user/[id]/_components/HistoryOverview.tsx
- src/app/(primary)/user/[id]/history/page.tsx
- src/app/(primary)/user/[id]/page.tsx
- src/components/Tab.tsx
- src/constants/user.ts
- src/hooks/useTab.ts
[#61] 히스토리 페이지 퍼블리싱
`/user/1` 페이지로 접근하여 별점, 리뷰, 찜 등... 갯수가 나온 부분을 클릭하면 페이지 이동됩니다.
* 여러 페이지에 리스트 컴포넌트를 추가하다보니 List.Manager 리팩토링 및 해당 로직에 대한 공통 훅을 생성해야할 필요성을 느꼈습니다...
* 너무 과도하게 props 를 넘기는 것 같아 이 부분을 또 합성 패턴으로 변경해서 적용을 해보려고 해요... 합성 컴포넌트가 아니더라도 뭔가 더 좋은 방법이 없을까 고민이 되네욤... 흠 :\ 
* Tab 컴포넌트가 공통화되어서 만약 다음에 또 Tab을 사용할 일이 있거나 코드를 간소화 하고싶으시면 공통 로직을 활용해주시면 될 것 같습니다.
> [#61] 히스토리 페이지 퍼블리싱

- .eslintrc.js
- package.json
- src/app/(primary)/_components/LikeBtn.tsx
- src/app/(primary)/_components/LoginModal.tsx
- src/app/(primary)/_components/PickBtn.tsx
- src/app/(primary)/review/[id]/_components/AlcoholInfo.tsx
- src/app/(primary)/review/[id]/_components/ReviewDetails.tsx
- src/app/(primary)/review/[id]/page.tsx
- src/app/(primary)/review/_components/AlcoholInfo.tsx
- src/app/(primary)/review/_components/SelectFlavor.tsx
- src/app/(primary)/review/_components/TagsForm.tsx
- src/app/(primary)/review/modify/page.tsx
- src/app/(primary)/review/register/page.tsx
- src/app/(primary)/search/[category]/[id]/page.tsx
- src/app/api/ReviewApi.ts
- src/components/Button.tsx
- src/components/Modal.tsx
- src/components/PageModal.tsx
- src/store/modalStore.ts
- src/style/globals.css
- src/types/Review.ts
- src/utils/shareOrCopy.ts
- yarn.lock
* [#98] 공통 Modal 기능 구현 및 review에 공통 modal 적용
1. home에서 알콜 화면 클릭해서 이동 후 리뷰 작성하기에서 작성 중간에 뒤로가기 버튼 등 눌러서 확인 가능
2. 로그인 전, 리뷰 내에 로그인 필요한 버튼 누르면 확인 가능 
* 찜하기, 좋아요 컴포넌트에 업데이트 해주는 부분 함수 형태로 수정 적용 했습니다. 보시고 혜정님 사용하시는 곳에도 수정 부탁드려요!
* 전역 변수 라이브러리로 zustand 적용 했습니다.
* 공통 Modal에 text는 2줄도 있고 sub text도 있어서 children으로 적용했습니다. 모달이 confirm일 경우, 버튼 관련 함수명들에 고민을 많이했는데.... 사용하기 나름이라 생각되는 부분이라 보시고 보완했으면 하는 부분 있으면 알려주세요.
* 모달에 사용하는 text 스타일은 global로 따로 적용해뒀습니다.
* 리뷰 더 보기에 들어가는 모달은 조금 수정이 필요해서 추후 적용 예정입니다.
> [#98] 공통 Modal 기능 구현 및 review에 공통 modal 적용

- src/app/(primary)/review/[id]/_components/AlcoholInfo.tsx
- src/app/(primary)/search/[category]/[id]/_components/Review.tsx
- src/app/(primary)/search/[category]/[id]/page.tsx
- src/app/(primary)/search/[category]/[id]/reviews/page.tsx
- src/app/api/ReviewApi.ts
- src/types/Review.ts
- src/types/common.ts
* [#117] Review 더보기 리스트 공통 컴포넌트 적용 및 API 연동
1. home에서 알콜 화면 클릭해서 이동 후 '리뷰 더보기' 버튼 클릭해서 이동
* 카테고리 폴더 layout.tsx에 NavLayout 컴포넌트를 page.tsx로 옮겨주셔야할 것 같아요. 카테고리 안에 review 페이지에서 네브바가 안보여야해서요!
* 공통 type에 SORT_TYPE에서   BOTTLE_PRICE, GLASS_PRICE 수정했는데 혹시 혜정님 API랑  다르면 코멘트 부탁드려요.
* 다음 PR에서 optionModal 수정, 삭제하기에 modal 적용 예정입니다.
* 베스트 리뷰인지 여부를 보여줘야 하는데 아직 API에 반영이 안되어서 있어서 추후 적용 예정입니다.
> [#117] Review 더보기 리스트 공통 컴포넌트 적용 및 API 연동

- src/app/(primary)/layout.tsx
- src/components/List/ListItemRating.tsx
- src/store/modalStore.ts
* 별점 요청 API 연동
* 체크리스트
* 로그인 모달의 중복 렌더링 방지
* 별점 페이지에서 로그인 전/후 별점 매기기 체크
* 별점을 드래그해서 매기는 UX는 개선이 필요합니다. (별도 이슈 추가됨)
> [#116] 별점 요청 API 연동

- src/app/(primary)/review/[id]/_components/Reply/Reply.tsx
- src/app/(primary)/review/[id]/_components/Reply/ReplyInput.tsx
- src/app/(primary)/review/[id]/_components/Reply/ReplyList.tsx
- src/app/(primary)/review/[id]/page.tsx
- src/types/Reply.ts
*  [#138 ] Review 상세조회에 대댓글 리스트 및 대댓글 입력 로직 수정
1. localhost/review/35
* 답글 달기를 누르면 @username이 다른 색으로 나와야 하는데 아직 이건 해결을 못 했어요. 기능적인 문제가 아니라 추후 개발로 넘기려고 합니다..!
* 대댓글을 남기면 해당 댓글의 토글이 열리면서 남긴 대댓글이 보이는게 좋을 것 같은데, 해당 부분은 서버에서 추가적으로 id를 보내줘야 가능할 것 같아서 서버담당자와 이야기 후에 반영 예정입니다.
>  [#138] Review 상세조회에 대댓글 리스트 및 대댓글 입력 로직 수정

- src/app/(primary)/user/[id]/_components/ProfileImage.tsx
- src/app/(primary)/user/[id]/_components/UserInfo.tsx
- src/app/(primary)/user/[id]/edit/_components/EditForm.tsx
- src/app/(primary)/user/[id]/edit/page.tsx
- src/app/api/CommonApi.ts
- src/app/api/ReviewApi.ts
- src/app/api/UserApi.ts
- src/app/api/token/renew/route.ts
- src/components/Modal.tsx
- src/components/OptionDropdown.tsx
- src/store/modalStore.ts
- src/types/common.ts
- src/utils/ApiError.ts
- src/utils/S3Upload.ts
- src/utils/fetchWithAuth.ts
- src/utils/validate.ts
[#131] 프로필 수정 (닉네임 수정, 모달 로직 개선, 에러 response 개선)
* 체크리스트
* 모달 개선 -> 모달 스토어 사용시 일관성 유지를 위해 상태를 중앙집중화
* fetchWithApi 에서 error response 개선한 이유는, 서버에서 내려주시는 에러 code 접근을 위해선 response  객체에 접근해야하는데 fetch 는 axios 처럼 기본적으로 reponse 접근을 할 수 있게 되어있지 않아서 직접 response 를 throw 시켜버렸습니다.
- 닉네임 수정 (기본적인 유효성 검사, 중복에 대한 에러처리 O)
- 프로필 사진은 일단 삭제만.
* 너무 길어질 것 같아서 쪼개서 올립니다.
* 프로필 사진은 이미지 파일 업로드 할 수 있게 로직 추가해줘야됌 다음 pr 에 올릴게요
> [#131] 프로필 수정 (닉네임 수정, 모달 로직 개선, 에러 response 개선)

- src/app/(primary)/report/page.tsx
- src/app/(primary)/review/[id]/_components/Reply/Reply.tsx
- src/app/(primary)/review/[id]/_components/ReviewDetails.tsx
- src/app/(primary)/search/[category]/[id]/_components/Review.tsx
- src/app/api/ReportApi.ts
- src/components/List/OptionSelect.tsx
- src/types/Report.ts
*  [#111 ] 신고하기 페이지 퍼블리싱, 기능 추가 및 POST API 연결
리뷰, 댓글 등에서 '유저 신고' 버튼을 통해 페이지 이동 후 테스트 가능
* OptionSelect 컴포넌트에 값이 없는 기본 라벨값이 필요해서 추가 했습니다.
* router를 이용해서 url 쿼리에 안보여주고 이동하는 페이지로 값을 넘겨주는 방식이 없어진 것 같아서 신고하고 싶은 userId를 스토리지에 저장하는 방향으로 했는데 더 좋은 방법이 있으면 댓글 부탁드려요!
* 리뷰, 댓글 신고에 대한 분기가 추가적으로 필요한데 기획과 api가 없어서 추후 수정이 필요합니다.
* 이번주는 문의하기 작업 예정입니다.
* 추가적으로 기본적인 작업이 끝나면 회원만 접근이 가능한 페이지는 url 입력으로 접근했을 때 리다이렉트 되는 로직이 전체적으로 추가되야 할 것 같아요!
> [#111 ] 신고하기 페이지 퍼블리싱, 기능 추가 및 POST API 연결

- src/app/(primary)/layout.tsx
- src/app/api/AuthApi.ts
- src/app/api/token/renew/route.ts
- src/store/modalStore.ts
- src/utils/fetchWithAuth.ts
*  #176 
* 체크리스트
* 로그인 모달 띄우는 처리가 토큰은 있지만 만료된 경우에도 추가되어야 하는데 그렇지 않았음
* 로그인 후 리프레시 토큰 만료될 때까지 기다렸다가 체크
- api 요청을 쐈을 때 토큰이 만료되었으면 403으로 와야되는데 400으로 오는 케이스의 경우 현재 로직에 걸리지 않음
- 예를 들어 어떤 경우 액세스 토큰 만료시에 403이 아닌 400으로 상태코드가 날아오는 경우가 있는데 이 경우 정상 처리가 안되기 때문에 백엔드쪽과 조정 필요
- 다른 방식으로 에러처리가 되어 있는 경우 겹칠 수 있음 
- pick 버튼의 경우 에러가 발생하면 별도 모달을 띄워주도록 되어있는데 이 부분이 두 개의 모달이 겹치는 현상으로 발생
> [#176] 리프레시 토큰 갱신 안됨 이슈

- src/app/(custom)/layout.tsx
- src/app/(primary)/_components/Header.tsx
- src/app/(primary)/_components/SubHeader.tsx
- src/app/(primary)/inquire/register/page.tsx
- src/app/(primary)/layout.tsx
- src/app/(primary)/rating/page.tsx
- src/app/(primary)/report/_constants/index.ts
- src/app/(primary)/report/page.tsx
- src/app/(primary)/review/_components/TagsForm.tsx
- src/app/(primary)/review/_schemas/reviewFormSchema.ts
- src/app/(primary)/review/modify/page.tsx
- src/app/(primary)/review/register/page.tsx
- src/app/(primary)/search/[category]/[id]/page.tsx
- src/app/(primary)/search/page.tsx
- src/components/Button.tsx
- src/components/Navbar.tsx
- src/hooks/useAlcoholDetails.ts
- src/hooks/useCallOnce.ts
- src/hooks/useErrorModal.ts
*  [#190] API 응답 처리 전 중복 요청 방지 로직 구현 및 review 리팩토링
Alcohol, Review 관련 페이지에서 확인 가능
* header, footer px 추가 작업은 header가 배경색 연장으로 header는 각각 컴포넌트 별로 줘야 하는 상태입니다. 이번 pr에서는 footer는 layout에서 공통 적용고 제가 작업하는 페이지에는 각각 적용 완료했습니다. header는 user쪽만 확인해서 추가해주시면 될 것 같아요.
* review 페이지 관련해서 반복되는 코드 위주로 리팩토링 했습니다.
* POST, PATCH 진행 시에 중복 호출 불가능하게 hook 만들어서 적용했고 요청 후 응답이 있기 전까지는 loading 화면이 나옵니다. 제가 작업한 부분에는 모두 적용했고 혜정님 화면 중에도 필요한 부분이 있으시면 적용 부탁드려요.
* 이미지 업로드 로직도 반복 사용하는 곳이 많은데 이번에 작업한 곳이 많아서 다음 리팩토링에 진행 예정입니다.
* sespense를 이용한 loading 적용은 useEffect로 data를 가져오는 곳에서는 적용이 안되서 직접적으로 적용하는 방법으로 적용했습니다. 추후 가능한 sespense 사용 가능한 방향으로 api 호출을 바꿔보려고 합니다.
> [#190] API 응답 처리 전 중복 요청 방지 로직 구현 및 review 리팩토링

- src/app/(custom)/layout.tsx
- src/app/(custom)/login/page.tsx
- src/app/(primary)/review/_components/KakaoAddressMap.tsx
- src/app/(primary)/user/[id]/_components/SidebarHeader.tsx
- src/app/api/UserApi.ts
- src/types/types.d.ts
- src/utils/flutterUtil.ts
- src/utils/handleWebViewMessage.ts
- types.d.ts
[#185] 플러터 채널링 활성화 - 로그인시 device info 받아와서 서버로 전달
* 체크리스트
- 로그인이 되었을 때 flutter 특정 채널로 device 정보 전달
- 플러터에서 device token 정보 받아와서 로그인 화면에 띄워주도록 일단 추가 (확인용으로 추후 제거 예정)
- 인앱 웹뷰 상태인지 확인해서 웹브라우저모드, 웹뷰모드 분기처리하는 플러터 채널 추가 필요
* 디바이스 정보를 유저별로 저장하기 위해서 데이터를 보내주어야 함
* 웹에서는 테스트가 안되고 모바일에서만 가능합니다 일단.
* 웹뷰 여부 판단하는 채널 추가하여 빌드 된 이후 다시 노티 드릴게요
> [#185] 플러터 채널링 활성화 - 로그인시 device info 받아와서 서버로 전달

- src/app/(primary)/report/page.tsx
[HotFix]변경 안된 hook 이름 변경
이전 변경 시 빠진 부분이 있어 현대 빌드 버그 발생.
> [HotFix]변경 안된 hook 이름 변경

- src/app/api/AuthApi.ts
- src/app/api/UserApi.ts
- src/components/Navbar.tsx
- src/utils/checkTokenValidity.ts
- src/utils/fetchWithAuth.ts
* #241 
- 문제 상황
- 로그아웃 상태인데도 마이페이지 접속했다가, 뭘 하나 클릭해야 그제서야 로그인 알림 모달이 뜸
- 문제 원인
- 토큰이 만료되어 로그아웃 처리가 되야함에도, api 쏘기 전까지는 만료 여부를 모름
- 모든 api 가 토큰을 필요로 하지도, 토큰에 대한 유효성을 검사하지도 않음
- 기존 로직에서 확인하던 userData 는 로그인 이후 쭉 저장되는 것이라서 만료 여부 추적 X
- 해결  
-  마이 페이지 접근 전 토큰 검증 api 쏴서 만료 여부 체크
- 토큰 만료 이후 마이페이지/히스토리 페이지 Navbar 통해서 방문
* url 접근은 안막고 있는데, 어차피 웹에 공개될 일이 없기 때문에 넘어가도 될듯?
> [#241] 로그인 컨텍스트 QC 사항 수정

- src/app/(primary)/user/[id]/_components/SidebarHeader.tsx
- src/app/(primary)/user/[id]/_components/Timeline.tsx
- src/app/(primary)/user/[id]/page.tsx
* [Hotfix]User 페이지에 히스토리 컴포넌트와 sidebarHeader 겹침 수정
- 문제 상황
- sidebarHeader에 히스토리 및 네브바가 더 위로 나오는 문제
- 히스토리 더미데이터가 유저 히스토리에 그대로 나오는 문제
- 문제 원인
- 히스토리 컴포넌트, 네브바 그리고 sidebarHeader의 떠있는 값이 동일한 문제
- 더이데이터를 그대로 사용하고 있는 문제
- 해결  
-  z-index값 변경
- 더미데이터 주석 처리 후 []값 사용
- 유저페이지에서 확인 가능
* 유저 페이지에 히스토리 링크는 히스토리가 없을 때 안나오게 하려고 timeline 컴포넌트 안으로 옮겼습니다.
> [Hotfix] User 페이지에 히스토리 컴포넌트와 sidebarHeader 겹침 수정

- src/components/List/ListItem.tsx
- src/components/List/_components/ItemInfo.tsx
- src/components/Navbar.tsx
* [Hotfix] 별점, 검색 list item 레이아웃 깨짐 및 navbar active 조건 수정
- 문제 상황
- List : 사파리에서 별점 레이아웃이 깨지는 문제
- navbar : 어떤 페이지를 가든 홈도 항상 선택되어 있는 클래스 적용되는 문제
- 해결  
- List : 정확한 원인은 못 찾았어요... 사파리에서 스타일 적용 순서에 따라 달라지는 경우도 있을 수 있다고 하고 일단은
스타일을 전반적으로 사파리에서 문제없이 나오는 것이 확인된 스타일로 변경 
- navbar : home을 먼저 확인해서 적용되도록 조건 수정
- 검색, 별점 페이지에서 확인 가능
* ItemInfo에서 한글이름이 나오는 부분에 'whitespace-pre'가 적용되어 있었는데 없는게 레이아웃이 더 자연스러워서 제거했습니다. 혹시 꼭 있어야하는 클래스인지 확인 부탁드려요!
* 혹시라고 사파리에서 추가적인 스타일 문제가 있다면 공부 좀 해서 재발 방지 방안을 찾아야할 것 같아요.
> [Hotfix] 별점, 검색 list item 레이아웃 깨짐 및 navbar active 조건 수정

- src/app/(primary)/inquire/register/page.tsx
- src/app/(primary)/review/_components/form/ImagesForm.tsx
* #256
* 플러터 앨범 핸들링 함수 ImagesForm 컴포넌트 적용
* /inquire/register 경로에서 ImagesForm 이 ssr 로 적용되어, dynamic 으로 CSR 로 변환 (원인 모름)
* 이미지 등록도 핵심 기능이니깐...
- 위스키 하나 들어가서 리뷰를 남길 때 사진을 올려본다.
* 한번에 사진 여러장 올리는건 안됨요 ㅠ 플러터 로직 수정해야돼요
* 현재 플러터에서 앨범에서 사진 하나 선택 -> base64 변환 -> 웹뷰로 쏨 이라서 여러개 핸들링이 안됌
> [#256] 리뷰 카메라, 앨범 연동 추가 (플러터)

- src/app/(custom)/login/_components/SocialLoginBtn.tsx
- src/app/(custom)/login/page.tsx
- src/app/(primary)/user/[id]/_components/SidebarHeader.tsx
- src/app/api/AuthApi.ts
- src/app/api/auth/[...nextauth]/route.ts
- src/utils/ApiError.ts
- src/utils/getAppleToken.ts
* PR과 관련된 간단한 제목을 작성해주세요.
* 버셀 계정으로 테스트했을 때 애플 키 쪽 변경사항 적용 후 정상 로그인 확인
* 실제 로그인 되는지는 다시 올려봐야 알 수 있음 흑흑
* 탈퇴 후 재가입 - 구글 심사 대응 추가
* 로그인 페이지 > 소셜 로그인 확인
* 베이직 로그인 탈퇴처리 > 재로그인
* 소셜 로그인 탈퇴 회원 재가입의 경우 nextAuth 쪽 응답 로직 수정이 필요해 다시 PR 날리겠습니다.
> [#262] 소셜로그인 심사 대응 - 테스트 이후 로그인 버튼 복구 / 베이직 로그인 - 탈퇴 회원 재가입 처리

- src/store/modalStore.ts
모달 닫혔을 때, 이전 모달에 떠있던 subText 남아있는 현상
* 이 변경을 테스트하기 위한 절차를 설명해주세요.
* 예: 어떤 환경에서 테스트를 수행했는지, 어떤 방식으로 테스트를 진행했는지 등
* PR과 관련된 추가적인 정보가 있다면 여기에 기술해주세요.
> [Hotfix]: 모달 닫혔을 때, 이전 모달에 떠있던 subText 남아있는 현상

- src/app/(primary)/user/[id]/_components/FollowerListItem.tsx
- src/app/(primary)/user/[id]/_components/UserInfo.tsx
- src/app/(primary)/user/[id]/follow/page.tsx
- src/app/api/UserApi.ts
- src/hooks/useInfiniteScroll.ts
- src/hooks/useTab.ts
- src/types/User.ts
* [#273]
- api 스펙 변동 및 팔로잉/팔로우 조회인지에 따라서 값을 묘하게 다르게 내려줘서 수정해줌
* 팔로우를 했음에도 팔로잉 상태로 변경안되고, 팔로우를 해제했음에도 팔로잉 해제 상태로 변경이 안되는 것은
* 서버에서 조회중인 유저 기준으로 status 를 내려줘야 하는데
* 리스트에 나와있는 유저 기준으로 상태를 줘서 그러함. 수정 예정이라고 하심
> [#273] 팔로잉 페이지 변경된 api spec 적용

- src/app/(primary)/_components/HotList.tsx
- src/app/(primary)/_components/PickBtn.tsx
- src/app/(primary)/_components/TimeLineItem.tsx
- src/app/(primary)/history/page.tsx
- src/app/(primary)/review/[id]/_components/AlcoholInfo.tsx
- src/app/(primary)/review/[id]/_components/ReviewDetails.tsx
- src/app/(primary)/search/[category]/[id]/_components/AlcoholBox.tsx
- src/app/(primary)/search/[category]/[id]/_components/Review.tsx
- src/app/(primary)/search/[category]/[id]/page.tsx
- src/app/(primary)/search/[category]/[id]/reviews/page.tsx
- src/app/(primary)/user/[id]/_components/Timeline.tsx
- src/app/api/HistoryApi.ts
- src/app/layout.tsx
- src/queries/usePaginatedQuery.ts
- src/style/globals.css
- src/types/User.ts
- src/utils/fetchWithAuth.ts
- tailwind.config.ts
* [#324 ]
리뷰, home, history QC
- cache의 경우, 별도 옵션을 주지 않으면 fetchWithAuth와 react-query 모두 캐시를 저장하게 되어 있어서 무조건 캐시를 날리고 화면에 진입하면 api 호출 하도록 수정 했습니다. 이후에 고도화하면서 cache, staleTime은 페이지에 맞게 수정하면 좋을 것 같아요.
- 각 페이지에서 확인 가능
- 리뷰 비공개, 공개 부분이 지금 문제가 좀 있는데 오늘 안에 해결이 가능할지 미지수라 된 부분들 먼저 pr 올립니다.
> 리뷰, home, history QC

- src/app/(primary)/_components/AlcoholImage.tsx
- src/app/(primary)/_components/FlavorTag.tsx
- src/app/(primary)/_components/TimeLineItem.tsx
- src/app/(primary)/history/_components/HistoryEmptyState.tsx
- src/app/(primary)/history/_components/Timeline.tsx
- src/app/(primary)/review/[id]/_components/Reply/ReplyInput.tsx
- src/app/(primary)/review/_components/form/RatingForm.tsx
- src/app/(primary)/search/[category]/[id]/_components/Review.tsx
- src/app/(primary)/search/[category]/[id]/layout.tsx
- src/app/(primary)/search/[category]/[id]/page.tsx
- src/app/(primary)/user/[id]/_components/Timeline.tsx
- src/components/LinkButton.tsx
- src/components/List/ListItemRating.tsx
- src/components/StarRaiting.tsx
알콜 디테일 페이지 전체 스타일 수정 및 간단한 오류 수정
- [#354 ] 
- [#361 ]
- [#364 ] 
- [#374 ]
> 알콜 디테일 페이지 스타일 수정

- src/app/(primary)/review/[id]/_components/ReviewDetails.tsx
- src/app/(primary)/review/_components/form/AddressForm.tsx
- src/components/Search/SearchBar.tsx
- [#377 ]
아이폰 IOS가 18.4 업데이트 후 <Link> 태그로 감싸진 곳에 스타일 버그 및 클릭 이벤트가 아예 안먹는 버그가 있는 것으로 확인 했습니다. 
- 메인 페이지에서 검색 버튼 확인
- 리뷰 디테일 화면 또는 리뷰 작성 화면에서 '지도보기' 클릭
* Next.js의 <Link> 컴포넌트는 기본적으로 prefetch 기능을 활성화하여 페이지를 사전에 로드하는데 이 기능이 모바일 환경에서 터치 이벤트와 충돌하여 링크 이동이 방해한다는 이슈가 있어서 false 처리했습니다. IOS 18.4 업데이트에 따른 관련 이슈가 아직 해결 방법으로 올라온 건 없어서 이 방법이 안되면 route를 사용하는 방식으로 바꿔야할 것 같아요...!
> #377 아이폰 IOS 18.4 업데이트에 따른 링크 버그 수정

- src/app/(primary)/_components/AlcoholImage.tsx
- src/app/(primary)/_components/PopularCard.tsx
- src/app/(primary)/_components/TimeLineItem.tsx
- src/app/(primary)/inquire/[id]/page.tsx
- src/components/BaseImage.tsx
- src/components/List/ListItem.tsx
- src/components/List/ListItemRating.tsx
- src/components/List/_components/ItemImage.tsx
- #290 
현재 알콜 이미지를 불러오는 곳은 모두 BaseImage  또는 AlcoholImage 컴포넌트로 변경했습니다.
*Loading 스타일은 추후에 스켈레톤으로 변경되야해서 임시로 효과 적용했습니다.
*AlcoholImage랑 ItemImage을 하나로 합치고 싶었는데 묘하게 달라서 일단은 그대로 뒀습니다.
*api로 이미지를 받아오는 곳에만 해당 컴포넌트를 적용하려고 하는데 생각보다 많아서 서로 수정하는 코드에 보이면 변경하는 식으로 해야할 것 같아요.
*제가 생각한 방식으로만 만들어봐서 추가나 수정했으면 하는 부분이 있으면 코멘트 남겨주세요!
> [#290] Image 컴포넌트 개발

- src/app/(custom)/login/page.tsx
- src/app/(primary)/user/[id]/_components/SidebarHeader.tsx
- src/hooks/useWebViewInit.ts
- src/lib/DeviceService.ts
- src/types/types.d.ts
- src/utils/flutterUtil.ts
*[#303] 이용약관 외부 링크 핸들링 방식 변경
- flutter 에서 사용하는 url_launcher 가 a 태그 의 target = _blank 만 감지가 되네요.
- 애플 소셜로그인은 ios 에서만 노출되는 것으로 변경했어요.
- 추후 사름님 pc 에 플러터 세팅해서 테스트 가능하도록 실행 매뉴얼 전달드릴게요.
* 혹 다른 기능에서 외부 링크로 핸들링 해야 할 일 있으면 a 태그를 활용하면 될 것 같아요.
> [#303] 이용약관 외부 링크 핸들링 방식 변경 & 앱 플랫폼 감지 핸들러 추가

- package.json
- src/app/(primary)/user/[id]/_components/SidebarHeader.tsx
- yarn.lock
[#371] OS 상관없이 일관된 환경변수 사용을 위한 cross-env 추가 적용
env-cmd만 적용하면 현재 윈도우 환경에서는 작동을 하지 않아서 OS 상관없이 사용할 수 있도록 cross-env을 추가 적용.
윈도우 환경에서 실행.
> [#371] OS 상관없이 일관된 환경변수 사용을 위한 cross-env 추가 적용

- src/app/(primary)/history/_components/HistoryEmptyState.tsx
- src/app/(primary)/history/_components/Timeline.tsx
- src/app/(primary)/history/page.tsx
- src/components/Search/SearchBar.tsx
- [#342 ]
search bar 버그는 검색창에 keyword가 있는 상태에서 최근 검색 목록에 있는 값을 선택하면 filter는 잘 적용이 되는데 검색창 input에는 이전 keyword가 그대로 나와서 해당 부분 수정했습니다.
히스토리 페이지에서 확인 가능
> [#342] 히스토리 filter api 호출 개선

- package.json
- src/components/Navbar.tsx
- src/hooks/useLogin.ts
- src/hooks/useWebViewInit.ts
- src/types/types.d.ts
- src/utils/flutterUtil.ts
* 플러터 인터페이스 변경에 따른 업데이트
- 플러터에서 값을 주입시켜버리면, 주입되지 않은 경우(웹 개발환경) 플러터에 핸들러 메시지를 보내지 않아 기존에 발생했던 에러가 사라지게 됩니다. 더 간단한 방식이어서 플러터쪽 업데이트하면서 변경했어요.
- 버전과 맞지 않는 integrity 값이 있어서 변경했고, env 로 등록했으니 submodule 업데이트해서 적용하면 될 것 같아요. 
- Navbar 에 우선 적용. 더블 터치 및 터치시 UI적 피드백은 좀 더 개선이 필요할 것 같네요.
- 웹 개발환경에서 다시 모바일 디바이스 모드로 개발 가능.
* 지금 이슈가 이원화되어서 어디를 기준으로 브랜치를 발행해야될지 모르겠어요. 이제는 거의 앱 레파지토리 쪽에 등록된 이슈 위주로 돌아가는 것 같아서 그쪽 이슈 번호를 따라서 브랜치를 따는게 어떨까 생각중입니다. 괜히 두개로 나눈것같아서요..ㅋㅋ 의견주세요..
> 플러터 인터페이스 변경에 따른 업데이트

- src/app/(primary)/explore/_components/SearchBar.tsx
- src/components/Search/SearchBar.tsx
- src/hooks/useSearchInput.ts
* 인풋 키보드 UX 개선
* 엔터를 눌렀을 때 키보드가 자동으로 사라지지 않음 -> 입력시에 input ref 의 blur 처리가 되지 않은 것이 원인.
* SearchBar 가 2가지로 나뉘어져 있기 때문에 일단 커스텀 훅을 사용
* 로컬에서 앱 띄워서 체크. 엔터 눌러서 키보드 화면이 잘 사라지면 정상
* SearchBar 컴포넌트의 확장성을 고려하면 디자인을 커스텀하면서 공통 로직은 유지하는 헤드리스 방식으로 변경하는게 좋아보임.
* ~~일단 조금 복잡도가 높아보일 수 있으니 코드 구조 개선 후 정식 PR로 요청하겠음.~~
> 인풋 키보드 UX 개선

- src/components/Search/SearchBar.tsx
- src/hooks/useSearchInput.ts
---
name: Pull Request Template
about: Template for creating a new Pull Request
title: ''
labels: ''
assignees: ''
---
[Fix] 한글 검색 시 마지막 글자 중복 입력 버그 수정
* IME composition 이벤트 처리를 추가하여 한글 입력 시 마지막 글자가 중복되는 문제 해결
* 체크리스트
* 한글 입력 시 IME composition 중에 엔터를 누르거나 검색 버튼을 클릭하면, composition이 완료되기 전에 검색이 실행되어 마지막 글자가 중복 입력되는 버그 발생
* 예시: "럼릭" 입력 후 검색 시 → "럼릭릭"으로 검색됨
* IME를 사용하는 한글, 중국어, 일본어 등 모든 언어에서 발생하는 공통 이슈
1. 검색창에 한글로 "럼릭" 입력
2. 엔터키를 눌러 검색 실행 → "럼릭"으로 정확히 검색되는지 확인
3. 검색창에 한글로 "위스키" 입력
4. 검색 버튼 클릭 → "위스키"로 정확히 검색되는지 확인
5. 검색어 입력 후 삭제 버튼 클릭 → 정상적으로 초기화되는지 확인
* Related issue: #278 
* `isComposing` 플래그는 브라우저 네이티브 이벤트 속성으로, IME composition 상태를 나타냄
* `onClick` 사용 시 이벤트 순서: `mousedown` → `compositionend` → `blur` → `click`
> fix: 위스키 검색 시 마지막 글자 중복 입력 버그 수정 
