next.config.mjs

* next.config.mjs 중복 ' 작성으로 오류 수정
* 체크리스트
* 빌드 오류 수정
* yarn dev
빌드 및 로컬 실행 오류가 있어서 바로 머지 하겠습니다!

[Fix] Remove duplicate single quotes from hostname

---

src/app/(primary)/_components/HotList.tsx
src/app/(primary)/page.tsx
src/constants/common.ts

* Home page.tsx 서버 컴포넌트로 만들기 위한 컴포넌트 분리
* 체크리스트
* 최상위 page.tsx를 서버 컴버컴포넌트로 사용하기 위한 수정
* yarn dev
* 기존에 있는 코드를 분리만 한 작업으로 다음 작업을 위해 바로 머지하겠습니다!

Home page.tsx 서버 컴포넌트로 만들기 위한 컴포넌트 분리

---

src/app/(primary)/announcement/[id]/page.tsx
src/app/(primary)/announcement/layout.tsx
src/app/(primary)/announcement/page.tsx
src/app/(primary)/user/[id]/_components/SidebarHeader.tsx
src/app/(primary)/user/[id]/_constants/index.ts

[#81] 공지사항 페이지 UI
* 체크리스트
* 추가된 UI 반영
마이페이지 > 사이드 바에서 공지사항 클릭
* 원래는 사이드바 애니메이션도 추가하려고 했는데, 애니메이션은 전반적으로 손보면 좋을 것 같아서 별도 PR 로 만드는게 좋을 것 같습니다.

[#81] 공지사항 페이지 UI

---

src/app/(primary)/_components/LikeBtn.tsx
src/app/(primary)/_components/PickBtn.tsx
src/app/(primary)/review/[id]/_components/AlcoholInfo.tsx
src/app/(primary)/review/[id]/page.tsx
src/app/(primary)/review/_components/AlcoholInfo.tsx
src/app/(primary)/review/_components/SelectFlavor.tsx
src/app/(primary)/review/_components/TagsForm.tsx
src/app/(primary)/review/modify/page.tsx
src/app/(primary)/review/register/page.tsx
src/app/(primary)/search/[category]/[id]/page.tsx
src/components/Modal.tsx
src/store/modalStore.ts

*[#98] 반영 안된 commit 추가 
* 변경한 부분이 같이 머지가 안되서 추가 머지합니다.

[#98] 반영 안된 commit 추가 

---

src/app/(primary)/user/[id]/_components/UserInfo.tsx
src/app/(primary)/user/[id]/edit/_components/EditForm.tsx
src/app/(primary)/user/[id]/edit/page.tsx
src/app/(primary)/user/[id]/page.tsx
src/app/api/UserApi.ts
src/app/api/token/renew/route.ts
src/components/Navbar.tsx
src/types/User.ts

[#115] 유저 데이터 불러오기 API 연동
* 체크리스트
로그인 여부 확인을 위해 api 연동 작업 진행했습니다.
로그인 전/후 상태에서 Navbar '마이' 버튼을 누릅니다.

[#115] 유저 데이터 불러오기 API 연동

---

src/app/(primary)/review/[id]/_components/Reply/Reply.tsx
src/app/(primary)/review/[id]/_components/Reply/ReplyList.tsx
src/app/(primary)/review/[id]/_components/ReviewDetails.tsx
src/app/(primary)/review/[id]/page.tsx
src/app/api/ReplyApi.ts
src/types/Reply.ts

* [#134 ] Review 상세조회에 댓글, 대댓글 삭제 구현 및 API 연결
1. localhost/review/35
* 다음 이슈로 대댓글 로직 수정 전에 임시로 수정된 부분과 API 변경 후 작업 가능한 부분은 주석 남겼습니다.
* Modal도 대댓글 이슈와 같이 작업 예정입니다.

[#134 ] Review 상세조회에 댓글, 대댓글 삭제 구현 및 API 연결

---

src/app/(primary)/review/[id]/_components/Reply/ReplyInput.tsx
src/app/(primary)/review/[id]/_components/Reply/ReplyList.tsx
src/app/(primary)/review/[id]/_components/ReviewDetails.tsx
src/app/(primary)/review/[id]/page.tsx
src/app/(primary)/review/modify/page.tsx
src/app/(primary)/search/[category]/[id]/_components/Review.tsx
src/app/(primary)/search/[category]/[id]/page.tsx
src/components/LinkButton.tsx
src/types/Alcohol.ts
src/types/LinkButton.ts
src/types/Review.ts

*  [#146 ] Review 기본 기능 중 개발 부족 부분 추가 및 보완
1. localhost/3000
* 변경된 Modal 컴포넌트는 다음 PR에 적용해서 올리겠습니다. 다음주 월, 수 정도 예상합니다.
* API 관련된 부분은 서버와 확인이 필요한 부분으로 다음 보완 이슈에 적용할게요!

[#146 ] Review 기본 기능 중 개발 부족 부분 추가 및 보완

---

src/app/(primary)/layout.tsx
src/app/api/ReviewApi.ts
src/components/Modal.tsx
src/store/modalStore.ts

*  [#121 ] Modal, ModalStore 변경 반영
1. localhost/3000
* 기본에 커밋했던 내용이 있어서 같이 PR 생성합니다.

[#121 ] Modal, ModalStore 변경 반영

---

src/app/(primary)/_components/LikeBtn.tsx
src/app/(primary)/_components/PickBtn.tsx
src/app/(primary)/_components/Toggle.tsx
src/app/(primary)/_components/VisibilityToggle.tsx
src/app/(primary)/review/[id]/_components/Reply/ReplyInput.tsx
src/app/(primary)/review/[id]/_components/ReviewDetails.tsx
src/app/(primary)/review/_components/ContentForm.tsx
src/app/(primary)/search/[category]/[id]/_components/Review.tsx
src/app/api/ReviewApi.ts
src/components/Modal.tsx
src/types/Review.ts

*  [#146 ] 공개, 비공개 API 연결 및 toggle 컴포넌트 생성
리뷰 화면 및 알콜 화면 리뷰 리스트에 확인 가능
* 빌드 오류는 해당 pr 병합되면 모두 해결 될 것 같아요.

[#146 ] 공개, 비공개 API 연결 및 toggle 컴포넌트 생성

---

src/app/(primary)/_components/RecentSearch.tsx
src/app/(primary)/review/[id]/_components/ReviewDetails.tsx
src/app/(primary)/review/_components/AddressForm.tsx
src/app/(primary)/review/_components/KakaoAddressMap.tsx
src/lib/SearchHistoryService.ts

*  [#160] Review 주소 검색 지도보기 팝업 변경 및 검색 리스트 구현
리뷰 작성 및 수정에서 주소 검색 클릭
* SearchHistoryService관련해서 key를 인자, 파라미터에 추가했습니다.

[#160] Review 주소 검색 지도보기 팝업 변경 및 검색 리스트 구현

---

package.json
src/app/(custom)/login/page.tsx
src/app/api/auth/[...nextauth]/route.ts
src/utils/getAppleToken.ts
yarn.lock

* 애플 소셜로그인 (nextAuth) 적용
* 체크리스트

[#164] 애플 소셜 로그인

---

src/app/(primary)/review/[id]/_components/Reply/ReplyInput.tsx
src/app/api/AlcholsApi.ts
src/app/api/ReviewApi.ts

*  [#172  ] Review 내에 토큰 누락 API 버그 수정
알콜 상세 페이지, 리뷰 상세 페이지에서 확인 가능
* 리뷰 상세보기에 있는 좋아요 true -> false로 만드는 로직은 현재 백엔드 오류가 있어 정상 작동하지 않습니다. 동민님이 수정 중입니다.

[#172] Review 내에 토큰 누락 API 버그 수정

---

src/app/(primary)/rating/page.tsx
src/app/(primary)/search/_components/SearchContainer.tsx
src/app/(primary)/search/page.tsx
src/app/(primary)/user/[id]/my-bottle/page.tsx

* 마이보틀 API 연동
* 체크리스트
* 마이보틀 API 적용 및 변경된 UI 적용 (검색 컴포넌트)
* 마이페이지 하단 > 활동 히스토리 버튼

[#114] 마이보틀 API 연동

---

src/app/(primary)/inquire/register/page.tsx
src/app/(primary)/review/[id]/_components/ReviewDetails.tsx
src/app/(primary)/review/_components/AddressForm.tsx
src/app/(primary)/review/_components/KakaoAddressMap.tsx
src/app/(primary)/review/_components/SearchAddress.tsx
src/app/(primary)/review/modify/page.tsx
src/app/(primary)/review/register/page.tsx
src/app/api/AlcholsApi.ts
src/constants/common.ts
src/style/globals.css
src/types/Review.ts

*  [#173] Review 주소 관련 개선 및 버그 수정
리뷰 작성 페이지에서 확인 가능
* input 창이 커지는 버그는 로컬에서 확인이 안되서 병합 후 배포를 해봐야 할 것 같아요!

[#173] Review 주소 관련 개선 및 버그 수정

---

src/app/(custom)/layout.tsx
src/app/(custom)/login/page.tsx
src/app/(primary)/review/_components/KakaoAddressMap.tsx
src/app/(primary)/user/[id]/_components/SidebarHeader.tsx
src/app/api/UserApi.ts
src/lib/DeviceService.ts
src/types/types.d.ts
src/utils/flutterUtil.ts
src/utils/handleWebViewMessage.ts
types.d.ts

[#185] 플러터 채널링 수정
* 체크리스트
* ref 나 state 에 저장하면 reload 하면서 날아가버려서 로컬 스토리지에 저장해버렸습니다.
* 로그인하면 자동으로 보내지는데, 서버에서 확인해주셔야 됩니다.

 [#185] 플러터 채널링 수정 - device 정보 전송

---

src/app/(primary)/_components/Header.tsx
src/app/(primary)/review/register/page.tsx
src/components/Toast.tsx
src/hooks/useReviewAutoSave.ts
src/hooks/useToast.tsx
src/types/Review.ts

*  [#194] Review 임시저장 기능 구현
Review 작성에서 확인 가능
* 임시 저장 룰은 1분 마다 자동 저장, 최대 저장 가능 기간 3일입니다. alchol Id 1개당 1만 임시 저장이 가능합니다.
* 토스트 디자인은 임시로 반영해서 추후 디자인, 기획에 따라 변경 가능성 있습니다.

[#194] Review 임시저장 기능 구현

---

src/app/(custom)/login/page.tsx
src/app/api/AuthApi.ts
src/app/api/UserApi.ts

- #204 
* 체크리스트
- 에러 상태 해소, 실제 유저 정보 가져오도록 수정
* 로그인 페이지 > 게스트 로그인

[#204] 게스트 로그인 - 로그인 후 토큰에서 유저 정보 가져오기

---

src/app/(primary)/report/_constants/index.ts
src/app/(primary)/report/page.tsx
src/app/(primary)/review/[id]/_components/Reply/Reply.tsx
src/app/(primary)/review/[id]/_components/ReviewDetails.tsx
src/app/(primary)/search/[category]/[id]/_components/Review.tsx
src/app/api/ReportApi.ts
src/types/Report.ts

*  [#220] Review 신고하기 API 연결
리뷰 디테일, 알콜 디테일에 리뷰 리스트에서 신고하기 가능.
* 신고하기는 user, review, comment가 있을 것으로 예상하고 있습니다. 현재 comment만 API가 완성 전이라 현재 API 기준으로 공통 사용 가능한 부분 리팩토링했습니다.
* 1명의 user가 1개의 review에 신고 type과 상관없이 1번만 가능하게 현재 API가 개발되어 있어서 UI에서는 중복 신고의 경우 알림 modal이 나오게 해둔 상태입니다. 해당 부분은 기획 확인 후 변경 가능성이 있습니다.

[#220] Review 신고하기 API 연결

---

.github/workflows/deploy_workflow.yml

chore: change deploy target branch
- 배포 대상 브랜치를 릴리즈 브랜치로 변경 후 룰셋 추가

chore: change deploy target branch

---

.github/workflows/deploy_workflow.yml

2025-0105-1

---

src/app/(primary)/user/[id]/_components/SidebarHeader.tsx
src/app/(primary)/user/[id]/_components/Timeline.tsx
src/app/(primary)/user/[id]/page.tsx
src/app/api/AuthApi.ts
src/components/Navbar.tsx
src/utils/checkTokenValidity.ts
src/utils/fetchWithAuth.ts

regular release: 2025-02-11:open

---

README.md

순환선 충돌 문제 해결 

---

README.md

---
name: Pull Request Template
about: Template for creating a new Pull Request
title: ''
labels: ''
assignees: ''
---
* PR과 관련된 간단한 제목을 작성해주세요.
* 이 PR에서 수행된 주요 변경 사항을 나열해주세요.
* 체크리스트
* 이 변경이 필요한 이유와 배경을 설명해주세요.
* 이 변경을 테스트하기 위한 절차를 설명해주세요.
* 예: 어떤 환경에서 테스트를 수행했는지, 어떤 방식으로 테스트를 진행했는지 등
* PR과 관련된 추가적인 정보가 있다면 여기에 기술해주세요.

docs: simplify README by removing unnecessary sections

---

README.md

순환선 충돌 문제 해결

---

src/app/(custom)/layout.tsx
src/app/(custom)/login/page.tsx
src/app/(custom)/signup/page.tsx
src/app/api/AuthApi.ts
src/types/Auth.ts

* #254 
* 심사 위해서 게스트 로그인 걷어내고 신설
- 로그인, 회원가입 페이지
* PR과 관련된 추가적인 정보가 있다면 여기에 기술해주세요.

[#254] 베이직 로그인/회원가입 기능 신설

---

src/app/(custom)/layout.tsx
src/app/(custom)/login/page.tsx
src/app/(custom)/signup/page.tsx
src/app/api/AuthApi.ts
src/components/List/ListItem.tsx
src/components/List/_components/ItemInfo.tsx
src/components/Navbar.tsx
src/types/Auth.ts

[Release] 2025-0229

---

src/app/(primary)/review/[id]/_components/Reply/ReplyInput.tsx
src/app/(primary)/review/_components/OptionsContainer.tsx
src/app/(primary)/user/[id]/_components/SidebarHeader.tsx
src/components/BackDrop.tsx
src/style/globals.css

[Release] 2025-0213 - 01

---

src/app/(primary)/_components/LoginModal.tsx
src/app/(primary)/inquire/register/page.tsx
src/app/(primary)/review/[id]/_components/ReviewDetails.tsx
src/app/(primary)/search/[category]/[id]/_components/AlcoholBox.tsx
src/app/(primary)/search/page.tsx
src/components/List/ListItem.tsx
src/components/List/OptionSelect.tsx
src/components/List/_components/ItemInfo.tsx
src/components/Modal.tsx
src/components/Search/RecentSearch.tsx
src/components/Star.tsx
src/constants/common.ts
src/hooks/usePopularList.ts
src/style/globals.css
src/utils/categoryUtils.ts
tailwind.config.ts

* [#279] 
* [#280]
* [#299]
* 폰트 사이즈에 대한 높이가 다 달라서 일관성이 없었음.
* 카테고리 메뉴의 경우 검색페이지 이동 및 카테고리 쿼리값이 모두 대문자라 일관되게 수정함
- 로그아웃 상태에서 문의하기
- 로그인 상태에서 문의하기
- 검색어 있는 상태에서 뒤로가기, 검색어 남아있음
- 메인 카테고리 > 검색 카테고리 이동
- 남은 QC 도 순차적으로 올라올 예정

[#278] 검색페이지 QC 사항 반영 (#279, #280, #299)

---

src/app/(primary)/user/[id]/_components/FollowerListItem.tsx
src/app/(primary)/user/[id]/_components/UserInfo.tsx
src/app/(primary)/user/[id]/follow/page.tsx
src/app/api/UserApi.ts
src/hooks/useInfiniteScroll.ts
src/hooks/useTab.ts
src/types/User.ts

[#273] 팔로잉 페이지 변경된 api spec 적용 (#319)

[Release] 2025-0303:1

---

src/app/(primary)/user/[id]/edit/_components/EditForm.tsx
src/app/(primary)/user/[id]/edit/page.tsx
src/components/List/OptionSelect.tsx
src/components/OptionDropdown.tsx

* [#327]
* [#328]
* 체크리스트
* 닫기를 매뉴얼하게 해주어야만 되기 때문에, 공통 로직에서 처리하도록 수정해줌
* 검색페이지, 배포 후 앱에서 프로필 페이지로 이동해 옵션 셀렉터를 열고 아무 옵션이나 눌러보세요.
* 마이페이지 QC 에 다른 사항들은 중복 이슈 or 이미 수정된 이슈여서 제외하였습니다.

[#327] 마이페이지 QC

---

src/components/List/ListItemRating.tsx

* [#316]
* 별점페이지에서 클릭하여 상세페이지 이동
* 이미지, 술 정보 텍스트가 선택 영역입니다.
* 어제했는데 얘만 안올려서 따로 올립니다.

[#316] 별점 list item 눌렀을 때 상세페이지 이동

---

src/app/(primary)/_components/VisibilityToggle.tsx
src/app/(primary)/review/[id]/_components/ReviewDetails.tsx
src/app/(primary)/review/[id]/page.tsx
src/app/(primary)/search/[category]/[id]/_components/Review.tsx
src/app/(primary)/search/[category]/[id]/page.tsx
src/app/(primary)/search/[category]/[id]/reviews/page.tsx

* [#323 ]
* [#331 ]
* 체크리스트
* 낙관적 업데이트를 하니까 모달이 열리고 닫히면서 state 상태 업데이트가 되고 공개, 비공개 값이 원복이 되는 현상이 있었습니다. 해당 로직을 사용하는 곳이 많아서 안정성을 위해 보수적인 api 업데이트로 로직 변경했습니다.
* 리뷰 리스트에 어디서는 보이고 어디서는 안보이는 이슈는 캐시 저장없이 상시 api 호출로 변경해서 해결이 된 것으로 보입니다. 제 화면에서는 구현이 안되는 상태라... 배포 후에 QC 올린 팀원에게 확인이 필요할 것같아요!
* 323인데 착각해서 브렌치명을 232로 했습니다....;

[#323] 리뷰 공개, 비공개

---

src/app/(primary)/_components/AlcoholImage.tsx
src/app/(primary)/_components/PickBtn.tsx
src/app/(primary)/search/[category]/[id]/_components/AlcoholBox.tsx
src/components/Star.tsx

* [#353 ]
* [#286 ]
* [#348 ]
* 리뷰 상세 페에지에서 뒤로가기로 알콜 상세 페이지 이동 시, 화면이 비정상적으로 나오는 오류는 현재 모바일에서만 발생하는 현상으로 우선 z-index값으로 배경 오버레이보다 알콜박스가 먼저 나오게 수정해봤습니다. 배포 후 확인이 필요한 상태입니다.
* 알콜 상세 페이지 중에서 맨 위에 알콜 정보가 나오는 부분만 피그마에 맞춰 수정한 상태입니다.

알콜 상세 페이지 QC

---

src/app/(primary)/review/[id]/_components/ReviewDetails.tsx
src/app/(primary)/review/modify/page.tsx
src/app/(primary)/search/[category]/[id]/_components/Review.tsx
src/types/Review.ts

- [#376 ]
이전 api type으로 되어있었음.
리뷰 상세 페이지의 rating, tags 부분에서 확인 가능.

#376 리뷰 API에 맞춰서 type 수정

---

src/app/(primary)/history/page.tsx
src/app/(primary)/review/[id]/_components/ReviewDetails.tsx
src/app/(primary)/review/[id]/page.tsx
src/app/(primary)/review/_components/form/AddressForm.tsx

- [#286 ]
- [#377 ]
* Link를 통한 외부 이동 버튼은 아예 작동을 안하는 상태
* 리뷰 상세, 리뷰 작성에서 지도보기 클릭
Header 부분이 이상하게 나오는 부분은 모바일에서만 한정적으로 나는 오류라 스타일을 찍어 볼 수가 없어서 일단 감으로 수정을 해보고 있어요ㅠㅠ

#286, #377 

---

src/app/(primary)/history/page.tsx
src/app/(primary)/review/[id]/_components/ReviewDetails.tsx
src/app/(primary)/review/[id]/page.tsx
src/app/(primary)/review/_components/form/AddressForm.tsx
src/app/(primary)/search/[category]/[id]/page.tsx

header 영역 및 외부 링크 오류

---

src/app/(custom)/layout.tsx
src/app/(custom)/login/page.tsx
src/app/(primary)/layout.tsx
src/app/api/AuthApi.ts
src/app/api/auth/[...nextauth]/route.ts
src/app/api/login/route.ts
src/app/api/oauth/kakao/route.ts
src/hooks/useAppSocialLogin.ts
src/hooks/useLogin.ts
src/hooks/useWebViewInit.ts
src/lib/AuthService.ts
src/types/Auth.ts
src/types/types.d.ts
src/utils/flutterUtil.ts

- [#274] 소셜로그인 플러터 모듈 구현하여 UX 개선 #302 
- 작업 진행상황 공유를 위해 미리 열어두었습니다.
- 아래 PR 과 동시 진행중입니다.
https://github.com/bottle-note/bottle-note-official-app/pull/83

[#274] 소셜로그인 플러터 모듈 구현하여 UX 개선 #302

---

src/app/(primary)/_components/CategoryList.tsx
src/app/(primary)/_components/PopularCard.tsx
src/components/LinkButton.tsx
src/components/Star.tsx

- [#350 ]
- [#358 ]
- [#365 ]
- [#366 ]
기획 변경에 따른 수정 및 QC
메인 화면에서 확인 가능

[#350] 메인페이지 스타일 QC

---

src/app/(custom)/layout.tsx
src/app/(custom)/login/page.tsx
src/app/(primary)/layout.tsx
src/app/api/AuthApi.ts
src/app/api/auth/[...nextauth]/route.ts
src/app/api/login/route.ts
src/app/api/oauth/kakao/route.ts
src/hooks/useAppSocialLogin.ts
src/hooks/useLogin.ts
src/hooks/useWebViewInit.ts
src/lib/AuthService.ts
src/types/Auth.ts
src/types/types.d.ts
src/utils/flutterUtil.ts

Revert "Revert "[#274] 소셜로그인 플러터 모듈 구현하여 UX 개선 #302 (#372)" (#390)"

---

src/app/(primary)/history/_components/filter/FilterSideModal.tsx
src/app/(primary)/history/page.tsx
src/app/(primary)/review/[id]/_components/ReviewDetails.tsx
src/app/(primary)/review/_components/OptionsContainer.tsx

- #360 
- #362 
- #363 
- #407 
* 피그마에 맞춰서 스타일 수정

[#407] 리뷰 이미지 버그 및 스타일 수정

---

package.json
yarn.lock

- [#371 ]
* 환경에 따른 요청 api 분리를 위한 작업
* 환경변수 파일명은 .env.development, .env.production입니다.

[#371] 환경변수 분리에 따른 build 커맨드 수정

---

package.json
src/app/(primary)/_components/PopularList.tsx
src/app/(primary)/history/_components/HistoryEmptyState.tsx
src/app/(primary)/history/_components/Timeline.tsx
src/app/(primary)/history/page.tsx
src/app/(primary)/user/[id]/_components/Timeline.tsx
src/components/Skeletons/SkeletonBase.tsx
src/components/Skeletons/custom/PopularSkeleton.tsx
src/components/Skeletons/custom/TimelineSkeleton.tsx
src/hooks/usePopularList.ts
src/types/Popular.ts

- [#429 ]
스켈레톤 관리를 위해 따로 폴더를 만들었습니다.
스켈레톤 폴더 안에는 공통(ex. userImage, basicItem 등)으로 사용될 것들을 추가하고
custom에는 공통 사용이 아닌 것들을 추가하는 걸로 구분했습니다.
기록 페이지, 마이 페이지에서 확인 가능

[#429] 기록 페이지 스켈레톤 적용 및 스켈레톤  리팩토링

---

src/app/(primary)/_components/AlcoholCard.tsx
src/app/(primary)/_components/PopularList.tsx
src/components/Skeletons/custom/PopularSkeleton.tsx
src/components/Star.tsx

- [#438 ]
메인 화면에서 확인 가능
* Star 컴포넌트에 점수가 없을 때 '-'가 나오는데 지금 icon 사이즈에 따라서 위치가 조금씩 달라지더라고요. 일단 임시적으로 수정을 하기는 했는데 안되는 곳들도 있어서 별도 이슈 생성했습니다. https://github.com/bottle-note/bottle-note-frontend/issues/439

[#438] '최근에 본 위스키' 수정

---

package.json
pnpm-lock.yaml

cross-platform 지원을 위한 shx 적용
cp는 window에서 작동을 안해서 추가했습니다.

cross-platform 지원을 위한 shx 적용

---

pnpm-lock.yaml
src/app/(primary)/_components/AlcoholCard.tsx
src/app/(primary)/explore/_components/ReviewCard.tsx
src/app/(primary)/review/[id]/_components/ReviewDetails.tsx
src/app/(primary)/search/[category]/[id]/_components/AlcoholBox.tsx
src/app/(primary)/user/[id]/my-bottle/_components/RatingsListItem.tsx
src/components/Star.tsx

- [#439 ]
통일된 레이아웃 사용을 위한 수정
검색, 알콜 디테일 페이지 등에서 확인 가능

[#439] Star 컴포넌트 개선

---

src/app/(primary)/inquire/[id]/page.tsx
src/app/(primary)/inquire/page.tsx
src/app/(primary)/review/[id]/_components/ReviewDetails.tsx
src/app/(primary)/user/[id]/_components/SidebarHeader.tsx
src/app/(primary)/user/[id]/my-bottle/page.tsx
src/components/List/List.tsx
src/components/Skeletons/custom/AlcoholDetailsSkeleton.tsx
src/components/Skeletons/custom/ReviewDetailsSkeleton.tsx

- [#459 ]
* List의 isEmpty 부분 둘러보기 하면서 수정됐는데 조건 반영이 안된 곳이 있어서 수정한다고 했는데 혹시 다른 부분에도 사용중이면 수정 부탁드려요!
* 공지사항도 제가 같이 수정했어요.

[#459] text, style  관련 개선사항

---

src/app/(primary)/explore/_components/Header.tsx
src/app/(primary)/explore/_components/SearchBar.tsx
src/app/(primary)/explore/_components/WhiskeyExploreList.tsx
src/app/(primary)/explore/page.tsx
src/components/Navbar.tsx

[Release] 2025-0605:4

---

src/app/(primary)/_components/CategoryList.tsx
src/app/(primary)/page.tsx
src/app/(primary)/user/[id]/_components/HistoryOverview.tsx
src/app/(primary)/user/[id]/_components/UserInfo.tsx
src/app/(primary)/user/[id]/page.tsx

- [#355 ]
- [#356 ]
- [#357 ]
기획 요청 및 QA
이슈에 있는 간단한 스타일 수정건도 같이 처리했습니다.

[#355, #356, #357] 스타일 수정

---

src/app/(primary)/_components/SidebarHeader.tsx
src/lib/FocusScrollProvider.tsx
src/lib/Providers.tsx
src/utils/flutterUtil.ts

* https://github.com/bottle-note/bottle-note-official-app/issues/158
* 키보드 입력시 웹뷰 화면 이동 버그 개선
* https://github.com/bottle-note/bottle-note-official-app/issues/157
* 개발 <-> 상용 스위치
* 모바일 환경에서 자동 스크롤 되지 않는 불편함이 있음.
* 플러터에서 핸들링하는 것보다 웹뷰에서 하는게 더 권장되는 방법 && 더 간단
* 환경스위치는 요청사항이 있었음, 앱에서 바로 개발 환경을 볼 수 있게 수정, 특정 계정에만 적용되도록 api 추가 이후 변경 필요
* 리뷰에서 포커스하세요.
* 현재 로그인 페이지에서도 동일한 문제가 있는데 여긴 베이직 로그인을 걷어낼 예정이라 따로 안건들였어요. 추후에 필요해진다면, 스크롤이 현재 화면의 height 에 영향을 받아서 높이가 고정값이면 안될것같아요.

[#158] 키보드 입력시 웹뷰 화면 이동 버그 개선 외.

---

src/app/(primary)/_components/AlcoholImage.tsx
src/app/(primary)/review/[id]/_components/AlcoholInfo.tsx
src/app/(primary)/review/[id]/_components/Reply/ReplyInput.tsx

리뷰에서 api 계속 호출하는 오류 수정
input에서 계속 업데이트가 되면서 계속 렌더링 되네요....ㅎㅎ
리뷰 상세, 리뷰 작성에서 확인 가능

[Fix] Applied memoization to child components of review

---

src/app/(primary)/_components/AlcoholImage.tsx
src/app/(primary)/review/[id]/_components/AlcoholInfo.tsx
src/app/(primary)/review/[id]/_components/Reply/ReplyInput.tsx

[Release] 2025-0619:2

---

src/app/(primary)/review/_components/AlcoholInfo.tsx
src/app/(primary)/review/_components/ReviewHeaderLayout.tsx
src/app/(primary)/review/_components/form/AddressForm.tsx
src/app/(primary)/review/_components/form/ContentForm.tsx
src/app/(primary)/review/_components/form/ImagesForm.tsx
src/app/(primary)/review/_components/form/PriceForm.tsx
src/app/(primary)/review/_components/form/ReviewForm.tsx
src/app/(primary)/review/_components/form/TagsForm.tsx
src/app/(primary)/review/modify/page.tsx
src/app/(primary)/review/register/page.tsx
src/app/(primary)/search/page.tsx

- [#484 ]
기획 변경에 따른 수정
리뷰 작성, 수정 페이지에서 확인 가능
리팩토링 필요한 곳들이 있는데 이번주는 회사가 바빠서 좀 어려울 것 같고 다음주에 해야할 것 같아서 변경 요청 사항만 수정해서 올려요!

[#484] 리뷰 수정 v1.1

---

src/app/(custom)/login/page.tsx
src/app/(primary)/explore/_components/ReviewExploreList.tsx
src/app/(primary)/explore/_components/SearchBar.tsx
src/app/(primary)/explore/_components/WhiskeyListItem.tsx
src/app/(primary)/explore/page.tsx
src/style/globals.css

[Release] 2025-0629:1

---

src/app/(primary)/_components/LikeBtn.tsx
src/app/(primary)/_components/PickBtn.tsx
src/app/(primary)/explore/_components/ReviewExploreList.tsx
src/app/(primary)/explore/_components/ReviewListItem.tsx
src/app/(primary)/review/[id]/_components/AlcoholInfo.tsx
src/app/(primary)/review/[id]/_components/ReviewDetails.tsx
src/app/(primary)/review/_components/ReviewHeaderLayout.tsx
src/app/(primary)/search/[category]/[id]/_components/AlcoholBox.tsx
src/app/(primary)/search/[category]/[id]/_components/Review.tsx
src/app/(primary)/search/[category]/[id]/page.tsx
src/app/(primary)/user/[id]/my-bottle/_components/PicksListItem.tsx
src/app/api/AlcholsApi.ts
src/app/api/RateApi.ts
src/components/List/List.tsx
src/components/List/ListItem.tsx
src/components/List/ListItemRating.tsx
src/components/StarRaiting.tsx
src/constants/common.ts
src/hooks/useDebounceAction.ts

- [#437 ]
불필요한 API 호출 줄이고 사용자의 사용성 개선
* 현재 디바운스가 적용 시간은 2초입니다.

[#437] 별점, 찜하기, 좋아요 로직에 Debounce 적용

---

src/app/(primary)/_components/PopularList.tsx
src/app/(primary)/_components/SubHeader.tsx
src/app/(primary)/explore/_components/ReviewExploreList.tsx
src/app/(primary)/explore/_components/ReviewListItem.tsx

- [#505 ]
* 리뷰 둘러보기 staleTime을 5분으로 한 이유가 있을까요? 리뷰 업데이트하고 바로 업데이트 반영이 안되서 5분을 제거 했는데 혹시 이유가 있으면 원복 할게요!

[#170] 화면 깨지는 스타일 수정

---

src/app/(primary)/_components/PopularList.tsx
src/app/(primary)/_components/SubHeader.tsx
src/app/(primary)/explore/_components/ReviewExploreList.tsx
src/app/(primary)/explore/_components/ReviewListItem.tsx

[Release] 2025-0803:1

---

src/app/(primary)/_components/Toggle.tsx
src/app/(primary)/_components/VisibilityToggle.tsx
src/app/(primary)/search/[category]/[id]/_components/ReviewItem.tsx
src/app/(primary)/search/[category]/[id]/page.tsx
src/app/(primary)/search/[category]/[id]/reviews/page.tsx

[#509] text 사이즈 추가 수정

---

src/app/(primary)/explore/_components/ReviewListItem.tsx

- [#509] 둘러보기 리뷰 content에 dangerouslySetInnerHTML 적용
기획 요청

[#509] 둘러보기 리뷰 content에 dangerouslySetInnerHTML 적용

---

next.config.mjs

백엔드 요청으로image url에 cloudfront.net  추가

[Feat] add cloudfront.net to remote image patterns

---

next.config.mjs

[[Fix] update cloudfront.net hostname to support wildcard patterns

[Fix] update cloudfront.net hostname to support wildcard patterns

---

src/app/api/AuthApi.ts
src/hooks/useAppSocialLogin.ts
src/lib/auth/handler.ts

* 변경된 카카오 로그인 api 대응
* 체크리스트
* 로그인 방식 변경
* 개발로 올리고 테스트 앱에서 테스트 가능

변경된 카카오 로그인 api 대응

---

src/app/(primary)/settings/page.tsx
src/components/LinkButton.tsx
src/components/Search/SearchBar.tsx

[#519] 간단한 스타일 수정

---

public/icon/plus-white.svg
src/app/(primary)/search/[category]/[id]/_components/AlcoholBox.tsx
src/app/(primary)/search/[category]/[id]/_components/FloatingReviewBtn.tsx
src/app/(primary)/search/[category]/[id]/page.tsx
src/app/(primary)/search/[category]/[id]/reviews/page.tsx
src/app/(primary)/settings/config.ts
src/app/(primary)/settings/page.tsx
src/components/Navbar.tsx
src/hooks/useReviewWrite.ts
src/hooks/useScrollState.ts

- [#528 ]
- [#529 ]
기획 요청에 따른 변경
- 리뷰 작성 로직은 저희 어플의 메인 기능이라 향후에 여기 저기 추가 될 가능성도 생각해서 로직이 복잡하지는 않지만 관리 용이하게 별도 hook으로 따로 만들었습니다.

[#528] navBar 스트롤 적용 및 리뷰 작성 플로팅 버튼 추가

---

src/app/(primary)/search/[category]/[id]/_components/FloatingReviewBtn.tsx

[Modify] 리뷰 작성 버튼 구현 수정

---

src/app/(primary)/search/[category]/[id]/_components/FloatingReviewBtn.tsx
src/app/(primary)/settings/page.tsx

개발 전환 코드 원복
모달 등을 더 추가했었는데 생각대로 안되서 기존 코드로 원복

개발 전환 코드 원복

---

public/icon/plus-white.svg
src/app/(primary)/search/[category]/[id]/_components/AlcoholBox.tsx
src/app/(primary)/search/[category]/[id]/_components/FloatingReviewBtn.tsx
src/app/(primary)/search/[category]/[id]/page.tsx
src/app/(primary)/search/[category]/[id]/reviews/page.tsx
src/app/(primary)/settings/config.ts
src/app/(primary)/settings/page.tsx
src/components/BaseImage.tsx
src/components/Navbar.tsx
src/hooks/useReviewWrite.ts
src/hooks/useScrollState.ts

[Release] 2025-0907:1 

---

src/components/Search/SearchContainer.tsx

- [#535 ]
* 이 PR에서 수행된 주요 변경 사항을 나열해주세요.

검색 input 스크롤 되는 오류 수정

---

src/components/ImageModal.tsx
src/components/Search/SearchContainer.tsx
src/hooks/useBlockScroll.ts

[#535] 검색 스크롤 방지 및 이미지 전체 보기 수정

---

src/components/ImageModal.tsx
src/components/Search/SearchBar.tsx
src/components/Search/SearchContainer.tsx
src/hooks/useBlockScroll.ts
src/hooks/useSearchInput.ts

---
name: Pull Request Template
about: Template for creating a new Pull Request
title: ''
labels: ''
assignees: ''
---
* PR과 관련된 간단한 제목을 작성해주세요.
* 이 PR에서 수행된 주요 변경 사항을 나열해주세요.
* 체크리스트
* 이 변경이 필요한 이유와 배경을 설명해주세요.
* 이 변경을 테스트하기 위한 절차를 설명해주세요.
* 예: 어떤 환경에서 테스트를 수행했는지, 어떤 방식으로 테스트를 진행했는지 등
* PR과 관련된 추가적인 정보가 있다면 여기에 기술해주세요.

[Release] 2025-0930
